pactus-project/pactus-wallet

.editorconfig
packages/wallet/src/wallet.ts
tests/wallet/wallet.test.ts

@alidevjimmy 
The tests should work, but I can't compile and test them. Please fix them

feat: derive new address

---

README.md

docs: update the README for the Pactus Wallet

---

.github/workflows/semantic-pr.yml

This PR adds the Semantic PR Validation action.

ci: add Semantic PR Validation action

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR adds the template for issues and pull requests.

chore: add GitHub templates

---

packages/wallet/README.md
packages/wallet/src/wallet-manager.test.ts

feat: export wallet data as json format

---

.editorconfig
.github/workflows/deploy.yml

This PR deploy beta version on wallet-beta.pactus.org.

ci(github): deploy beta version

---

packages/wallet/src/testdata/wallet_version_3

This PR updates the wallet test data.

test(wallet): update wallet tests

---

CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md

This PR adds the contributing document and update the readme.

docs: add contributing doc and update readme

---

.github/workflows/deploy.yml

change npm to yarn in deploy.yml

fix: change npm to yarn in deploy.yml

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
package.json

This PR adds the testing and linting actions.
TODO: define linting targets. @phoenixit99

ci(github): add testing action

---

packages/wallet/src/manager.test.ts
packages/wallet/src/manager.ts
packages/wallet/src/wallet.test.ts

test(wallet): fix broken test in case load wallet from encrypt keystore
Fixes # (issue)

test(wallet): fix broken test in case load wallet from encrypt keystore

---

packages/wallet/src/encrypter/encrypter.test.ts
packages/wallet/src/encrypter/encrypter.ts
packages/wallet/src/encrypter/params.ts
packages/wallet/src/manager.test.ts
packages/wallet/src/manager.ts
packages/wallet/src/types.ts
packages/wallet/src/wallet.test.ts
packages/wallet/src/wallet.ts

This PR fixes the vault encryption and covers it buy tests.

fix(wallet): fix vault encryption

---

packages/wallet/package.json
packages/wallet/src/utils.test.ts
packages/wallet/src/utils.ts
packages/wallet/src/wallet.test.ts
packages/wallet/src/wallet.ts

This PR converts the public key to string using `bech32m`

fix(wallet): convert public key to string

---

apps/web/next.config.ts
apps/web/src/components/add-account-modal/index.tsx
apps/web/src/components/header/index.tsx
apps/web/src/components/sidebar/style.css
apps/web/src/scenes/dashboard/index.tsx
apps/web/src/scenes/wallet/index.tsx
apps/web/src/wallet/provider/index.tsx
packages/wallet/src/manager.ts
packages/wallet/src/wallet.ts

In the production environment, the wallet was not loading securely due to a missing condition check for an empty initial wallet. As a result, the provider was unable to correctly determine the wallet’s state and redirect the user to the /get-started page.
This PR resolves the issue by properly handling the empty wallet condition, ensuring that the provider can accurately verify the wallet's status and navigate users accordingly.

fix: wallet loading issue in production

---

apps/web/src/scenes/get-started/components/add-wallet/index.tsx
apps/web/src/scenes/get-started/components/choose-name-wallet/index.tsx
apps/web/src/scenes/get-started/components/import-wallet/index.tsx
apps/web/src/scenes/get-started/components/import-wallet/style.css

This PR adds the ability for users to import an existing wallet using their 12 or 24-word recovery phrase, with an intuitive user interface and enhanced usability features.#83
- Created ImportWallet component with support for both 12 and 24-word seed phrases
- Implemented intelligent paste handling that correctly processes pasted recovery phrases in multiple formats
- Added user-friendly validation to ensure all seed phrase fields are filled before proceeding
- Improved UX with visual guidance and tooltips for users
- Added smooth navigation to continue to master password setup after successful phrase entry
- Dynamic adjustment based on selected word count (12 or 24)
- Smart paste detection that automatically fills appropriate fields
- Clear visual indication of input state and validation …

feat: wallet recovery feature with enhanced seed phrase import functionality

---

apps/web/src/components/sidebar/index.tsx

Link to issues changed to `issues/new/choose`

chore: update link to issues

---

.husky/pre-commit
package.json
yarn.lock

chore: remove husky and lint-staged

---

packages/wallet/src/wallet.ts

This PR changes the schema to https for gRPC client

fix: use https schema for gRPC client

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
packages/wallet/package.json
yarn.lock

This PR fixes the build issue and add build action

ci: add build action

---

packages/wallet/src/utils.ts

This PR fixes a linting issue.

chore: fix linting issue

---

apps/web/src/components/address-infom-modal/index.tsx
apps/web/src/components/address-infom-modal/style.css
apps/web/src/components/modal/index.tsx
apps/web/src/components/modal/style.css
apps/web/src/components/password-modal/index.tsx
apps/web/src/components/password-modal/style.css
apps/web/src/components/sidebar/index.tsx
apps/web/src/scenes/dashboard/index.tsx
apps/web/src/scenes/get-started/components/welcome/index.tsx
apps/web/src/scenes/get-started/index.tsx
apps/web/src/scenes/wallet/index.tsx
apps/web/src/scenes/wallet/style.css
apps/web/src/utils/i18n/translations/en.ts
apps/web/src/wallet/hooks/use-account.ts
packages/wallet/src/utils.ts
packages/wallet/src/wallet.test.ts
packages/wallet/src/wallet.ts
yarn.lock

implement show address information 
fix #92

feat: implement show address information

---

apps/web/src/scenes/get-started/components/welcome/index.tsx
apps/web/src/scenes/get-started/components/welcome/style.css

enhance welcome title styling and prevent text wrapping

fix: enhance welcome title styling and prevent text wrapping

---

apps/web/src/utils/constants.ts
apps/web/src/utils/password-utils.test.ts
apps/web/src/utils/password-utils.ts
apps/web/src/utils/password-validator/index.test.ts
apps/web/src/utils/password-validator/index.ts

refactor: split define password and move rule to the constants file

---

packages/wallet/src/types/amount.ts
packages/wallet/src/types/transaction.ts
packages/wallet/src/wallet.test.ts
packages/wallet/src/wallet.ts

implement transfer broadcast transaction 
Relevant #87  , #142

feat(wallet): implement broadcast transaction

---

packages/wallet/jest.config.js
packages/wallet/src/storage/browser-storage.test.ts
packages/wallet/src/storage/jest-setup.ts
packages/wallet/src/storage/memory-storage.test.ts
packages/wallet/test-jsonrpc.ts

Update the test case for browser storage and memory storage 
Fixed #75

test: add test case for browser storage and memory storage

---

packages/wallet/src/wallet.ts
packages/wallet/test-jsonrpc.ts

This PR adds more public nodes to interact with Pactus.

chore: update JSON-RPC public nodes

---

apps/web/src/components/modal/index.tsx
apps/web/src/wallet/provider/index.tsx
packages/wallet/src/utils.ts

chore: remove border in loading, change error code

---

apps/web/src/components/common/Form/PasswordInput.tsx
apps/web/src/components/common/FormPasswordInput.tsx
apps/web/src/components/common/PasswordStrengthIndicator.tsx
apps/web/src/components/modal/index.tsx
apps/web/src/components/password-modal/index.tsx
apps/web/src/components/send/SendPreviewModal.tsx
apps/web/src/scenes/get-started/components/master-password/index.tsx
apps/web/src/wallet/provider/index.tsx
packages/wallet/src/utils.ts

chore: improve ui/ux for the password field

---

apps/web/src/assets/images/icons/link-icon.svg
apps/web/src/assets/images/icons/pacview-icon.svg
apps/web/src/components/address-infom-modal/index.tsx
apps/web/src/components/common/skeleton/Skeleton.tsx
apps/web/src/components/common/skeleton/index.css
apps/web/src/components/password-modal/index.tsx
apps/web/src/components/sidebar/index.tsx
apps/web/src/components/sidebar/style.css
apps/web/src/scenes/dashboard/index.tsx
apps/web/src/scenes/wallet/index.tsx
apps/web/src/utils/i18n/translations/en.ts
apps/web/src/wallet/hooks/use-balance.ts

feat(web): add buttons show wallet information and fix bug balance

---

apps/web/src/scenes/get-started/components/recovery-phrase/index.tsx
apps/web/src/scenes/get-started/components/recovery-phrase/style.css
package.json
yarn.lock

> This pull request updates the styling for seed word numbers to use a muted color for better distinction. It modifies `index.tsx` to add the `text-muted` class and updates `style.css` to define the muted styling.
Fixes # 160

fix: muted styling for seed word numbers

---

apps/web/src/components/common/PasswordStrengthIndicator.tsx
apps/web/src/components/password-modal/index.tsx
apps/web/src/components/send/SendForm.tsx

remove validate password on send form and password modal
Fixes #164

fix(web): remove validate password on send form and password modal

---

apps/web/package.json
apps/web/src/components/add-account-modal/index.tsx
apps/web/src/components/change-password-modal/ChangePasswordModal.tsx
apps/web/src/components/change-password-modal/index.ts
apps/web/src/components/common/Form/Form.tsx
apps/web/src/components/common/FormPasswordInput.tsx
apps/web/src/components/layout/MainLayout.tsx
apps/web/src/scenes/setting/General.tsx
apps/web/src/utils/i18n/translations/en.ts
apps/web/src/wallet/hooks/use-account.ts
packages/wallet/src/wallet.test.ts
packages/wallet/src/wallet.ts
yarn.lock

feat(web): update wallet password
Fixes #89

feat(web): update wallet password

---

apps/web/src/components/header/index.tsx
apps/web/src/components/setting-sidebar/SettingSidebar.tsx
apps/web/src/utils/i18n/translations/en.ts

This PR moves logout icon from header to settings page.
Fixes #122

refactor(header): move logout to settings

---

apps/web/src/components/command-search/index.tsx
apps/web/src/components/command-search/style.css
apps/web/src/components/sidebar/index.tsx

This PR implements search functionality.
Fixes #169

feat(sidebar): add command search component and integrate with sidebar

---

apps/web/package.json
apps/web/src/components/common/switch/Switch.tsx
apps/web/src/components/common/switch/index.ts
apps/web/src/components/send/SendForm.tsx
apps/web/src/utils/i18n/translations/en.ts
yarn.lock

> A clear description of what the pull request does.
Fixes #88

feat(web): bond transaction

---

.github/workflows/deploy.yml
packages/wallet/package.json
yarn.lock

This PR aims to publish the production website on git tags.

ci: publish the production website

---

.github/workflows/deploy.yml
apps/web/package.json
docs/deployment.md
packages/wallet/package.json

chore(version): bumping version to 0.5.0

---

apps/web/eslint.config.mjs
packages/wallet/eslint.config.mjs
packages/wallet/package.json
packages/wallet/src/types/wallet_info.ts
packages/wallet/src/wallet.test.ts
packages/wallet/src/wallet.ts

feat: encode private key with bech32m

---

apps/web/src/scenes/wallet/index.tsx

> A clear description of what the pull request does.
Fixes # (issue)

feat(web): add branding for qr code address

---

apps/web/src/components/bridge/index.tsx

feat: bridge pac using wrapto

---

apps/web/src/components/bridge/index.tsx
apps/web/src/components/receive/index.tsx
apps/web/src/components/send/SuccessTransferModal.tsx
apps/web/src/scenes/wallet/index.tsx
apps/web/src/utils/common.ts
apps/web/src/utils/constants.ts

Following the new proposal from https://github.com/pactus-project/PIPs/blob/main/PIPs/pip-42.md
We apply the new format for the QR Code 
fixed: #150

feat: qr format 

---

apps/web/src/components/transactions-history/index.tsx
apps/web/src/scenes/wallet/index.tsx
apps/web/src/services/transaction.ts

> A clear description of what the pull request does.
Fixes # (issue)

fix(web): fix call api loop

---

apps/web/package.json
docs/deployment.md
packages/wallet/package.json

chore(version): bumping version to 1.0.0

---

apps/web/src/wallet/hooks/use-balance.ts

fix: missing total balance overview section
